### ISSUE TITLE
requirements to use in react.js

### ISSUE THREAD

**Issue by iroth** [iddan/react-universal-markdown#4]
getting this error:
Module parse failed: /Users/iroth/projects/kang/kang-cms/frontend/node_modules/react-universal-markdown/src/Markdown.js Unexpected token (14:4)
You may need an appropriate loader to handle this file type.
|   const children = [...getChildren(node)];
|   return (
|     <NodeComponent {...{info, level, listType, listStart, title, destination}}>
|       {!children.length
|         ? node.literal

**Comment by iddan** [comment]
Currently this package requires transformation as it assumes it's being parsed by Metro Bundler. Will provide Webpack-friendly version soon. In the midtime you can include it in the whitelist of babel-loader

**Comment by iddan** [comment]
Fixed
